<link rel="stylesheet" href="{{ asset('dist-accommodation/css/bootstrap.min.css') }}">
<link rel="stylesheet" href="{{ asset('dist-accommodation/css/font-awesome.min.css') }}">
<link rel="stylesheet" href="{{ asset('dist-accommodation/css/select2.min.css') }}">
<link rel="stylesheet" href="{{ asset('dist-accommodation/css/bootstrap-datepicker.min.css') }}">
<link rel="stylesheet" href="{{ asset('dist-accommodation/css/bootstrap-timepicker.min.css') }}">
<link rel="stylesheet" href="{{ asset('dist-accommodation/css/bootstrap-tagsinput.css') }}">
<link rel="stylesheet" href="{{ asset('dist-accommodation/css/duotone-dark.css') }}">
<link rel="stylesheet" href="{{ asset('dist-accommodation/css/dataTables.bootstrap4.min.css') }}">
<link rel="stylesheet" href="{{ asset('dist-accommodation/css/iziToast.min.css') }}">
<link rel="stylesheet" href="{{ asset('dist-accommodation/css/fontawesome-iconpicker.min.css') }}">
<link rel="stylesheet" href="{{ asset('dist-accommodation/css/bootstrap4-toggle.min.css') }}">
<link rel="stylesheet" href="{{ asset('dist-accommodation/css/summernote-bs4.css') }}">
<link rel="stylesheet" href="{{ asset('dist-accommodation/css/style.css') }}">
<link rel="stylesheet" href="{{ asset('dist-accommodation/css/components.css') }}">
<link rel="stylesheet" href="{{ asset('dist-accommodation/css/spacing.css') }}">
<link rel="stylesheet" href="{{ asset('dist-accommodation/css/custom.css') }}">